{
  "stats": {
    "suites": 0,
    "tests": 1,
    "passes": 0,
    "pending": 0,
    "failures": 1,
    "start": "2025-04-06T12:21:21.747Z",
    "end": "2025-04-06T12:21:36.099Z",
    "duration": 14352,
    "testsRegistered": 1,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "33c42d8a-3d9d-4633-88a2-4b3b075ac4c2",
      "title": "",
      "fullFile": "cypress\\integration\\examples\\ExcelTest.js",
      "file": "cypress\\integration\\examples\\ExcelTest.js",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [
        {
          "title": "An uncaught error was detected outside of a test",
          "fullTitle": "An uncaught error was detected outside of a test",
          "timedOut": null,
          "duration": 3168,
          "state": "failed",
          "speed": null,
          "pass": false,
          "fail": true,
          "pending": false,
          "context": "{\n  \"title\": \"cypress-mochawesome-reporter-videos-failed\",\n  \"value\": \"cypress\\\\integration\\\\examples\\\\ExcelTest.js\"\n}",
          "code": "throw err;",
          "err": {
            "message": "TypeError: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cannot read properties of undefined (reading 'F_OK')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
            "estack": "TypeError: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Cannot read properties of undefined (reading 'F_OK')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at eval (node_modules/exceljs/dist/exceljs.min.js:3:0)\n    at new Promise (<anonymous>)\n    at Object.exists (node_modules/exceljs/dist/exceljs.min.js:3:0)\n    at M.readFile (node_modules/exceljs/dist/exceljs.min.js:3:0)\n    at _callee$ (cypress/integration/examples/ExcelTest.js:5:24)\n    at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:0)\n    at Generator.eval (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:0)\n    at Generator.eval [as next] (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:0)\n    at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:0)\n    at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:0)",
            "diff": null
          },
          "uuid": "1dd1effb-c2fa-4bf4-9fa6-ecce7cdd8210",
          "parentUUID": "33c42d8a-3d9d-4633-88a2-4b3b075ac4c2",
          "isHook": false,
          "skipped": false
        }
      ],
      "suites": [],
      "passes": [],
      "failures": [
        "1dd1effb-c2fa-4bf4-9fa6-ecce7cdd8210"
      ],
      "pending": [],
      "skipped": [],
      "duration": 3168,
      "root": true,
      "rootEmpty": false,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": false,
        "reportFilename": "mochawesome",
        "saveHtml": false,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "7.1.3"
    },
    "marge": {
      "options": {
        "overwrite": false,
        "html": false,
        "json": true,
        "reportDir": "cypress\\reports\\html\\.jsons"
      },
      "version": "6.2.0"
    }
  }
}